alter table public.pillbox_settings
    add column if not exists line_user_id text;

alter table public.pillbox_logs
    add column if not exists scheduled_time text;

create table if not exists public.pillbox_reminders (
    id bigint generated by default as identity primary key,
    device_id text not null references public.pillbox_settings(device_id) on delete cascade,
    slot_name text not null check (slot_name in ('morning', 'noon', 'evening', 'bedtime')),
    reminder_date date not null,
    sent_at bigint not null,
    unique (device_id, slot_name, reminder_date)
);

alter table public.pillbox_settings enable row level security;
alter table public.pillbox_logs enable row level security;
alter table public.pillbox_reminders enable row level security;

drop policy if exists "Allow anon access settings" on public.pillbox_settings;
drop policy if exists "Allow anon access logs" on public.pillbox_logs;

revoke all on public.pillbox_settings, public.pillbox_logs, public.pillbox_reminders
    from anon, authenticated;